---
sudo: false
language: ruby
cache: bundler
env: 
rvm:
- jruby-1.7.25
services:
- mysql
before_install:
- mysql -e 'CREATE DATABASE jdbc_streaming_db;'
matrix:
  include:
  - rvm: jruby-9.1.10.0
    env: LOGSTASH_BRANCH=master
  - rvm: jruby-1.7.25
    env: LOGSTASH_BRANCH=5.x
  fast_finish: true
install: true
script: ci/build.sh
jdk: oraclejdk8
